version: '3.8'

services:
  # Frontend - używamy gotowego obrazu Nginx
  frontend:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/public:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

  # Backend API
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - minio
      - elasticsearch
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/legal_assistant
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - ELASTIC_URL=http://elasticsearch:9200
      - JWT_SECRET=supersecret_replace_in_production
    networks:
      - app-network
    volumes:
      - ./backend:/app
    restart: unless-stopped

  # Baza danych
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=legal_assistant
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  # System plików
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - app-network
    restart: unless-stopped

  # Elasticsearch dla wyszukiwania
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - app-network
    restart: unless-stopped

  # Inicjalizator bazy danych i systemu plików
  init-services:
    build: ./init-services
    depends_on:
      - db
      - minio
      - elasticsearch
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/legal_assistant
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - ELASTIC_URL=http://elasticsearch:9200
    networks:
      - app-network
    restart: on-failure

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
  minio-data:
  elasticsearch-data:
